### ISSUE TITLE
`make` deriver sometimes not fully part of `ppx_deriving.std`?

### ISSUE THREAD

**Issue by smondet** [ocaml-ppx/ppx_deriving#124]
This has happened in a bunch of Docker and [Travis](https://travis-ci.org/hammerlab/biokepi/jobs/209075323) builds

It doesn't seem to happen in all cases just with `opam upgrade`, more from fresh installs.

    opam switch test403 --alias-of 4.03.0
    eval `opam config env`
    opam install ppx_deriving utop

Then in `utop`, deriving-make does not work:

```ocaml
ocaml# #require "ppx_deriving.std";;

ocaml# type t = { x: int } [@@deriving show];;
type t = { x : int; }
val pp : Format.formatter -> t -> unit = <fun>
val show : t -> string = <fun>

ocaml# type t = { x: int } [@@deriving make];;
Cannot locate deriver make
```

In `` `ocamlfind query ppx_deriving`/META``, that looks OK?

```
package "std" (
  version = "4.1"
  description = "Meta-package for all built-in derivers"
  requires  = "ppx_deriving.show ppx_deriving.eq ppx_deriving.ord"
  requires += "ppx_deriving.enum ppx_deriving.iter ppx_deriving.map"
  requires += "ppx_deriving.fold ppx_deriving.create ppx_deriving.make"
)

...

package "make" (
  version = "4.1"
  description = "[@@deriving make]"
  requires(-ppx_driver) = "ppx_deriving"
  ppxopt(-ppx_driver,-custom_ppx) = "ppx_deriving,./ppx_deriving_make.cma"
  requires(ppx_driver) = "ppx_deriving.api"
  archive(ppx_driver, byte) = "ppx_deriving_make.cma"
  archive(ppx_driver, native) = "ppx_deriving_make.cmxa"
  exists_if = "ppx_deriving_make.cma"
)
```

**Comment by smondet** [comment]
`make` by itself seems to have the problem:

```ocaml
ocaml# #require "ppx_deriving.make";;
ocaml# type t = { x: int } [@@deriving make];;
Cannot locate deriver make
```

**Comment by whitequark** [comment]
https://github.com/whitequark/ppx_deriving/commit/a4428407e974361d872e0a70e036bc7ee20e8467

**Comment by smondet** [comment]
Indeed with `opam pin add ppx_deriving https://github.com/whitequark/ppx_deriving.git` it works.

**Comment by smondet** [comment]
https://github.com/ocaml/opam-repository/pull/8656

**Comment by whitequark** [comment]
Looks like this is fixed in master and worked around for older versions, so closing.
