### ISSUE TITLE
Instruction on using ppx_deriving with jbuilder?

### ISSUE THREAD

**Issue by bikalgurung** [ocaml-ppx/ppx_deriving#134]
Hi,
I am attempting to use the latest github version of `ppx_deriving` with jbuilder. However, it doesn't seem to be working with the stanza `(preprocess (pps (ppx_deriving.std)))`. Could you please provide some guidance on how one can use `ppx_deriving` with `jbuilder`.

Thanks.

**Comment by whitequark** [comment]
ppx_deriving supports build systems that use ocamlfind. This looks like an issue with jbuilder's ocamlfind support, and should be addressed in jbuilder.

**Comment by diml** [comment]
I had a quick look at this following the jbuilder ticket. In order for ppx_deriving to work with the ocaml-migrate-parsetree driver, the `Driver.register` must go in `ppx_deriving.ml`. Only the `Driver.run_main ()` should be in `ppx_deriving_main.ml`.

**Comment by whitequark** [comment]
@diml Ack, seems like an easy fix.

@bikalgurung Do you think you can test this change and send a PR? I'm afraid I won't have time to learn jbuilder, set up a test environment, etc, any time soon.

**Comment by bikalgurung** [comment]
@whitequark sure. I will give it a try.

**Comment by emillon** [comment]
Now that 4.2 is released, you should be able to use `ppx_deriving` with `jbuilder` using what you said:

```
(preprocess (pps (ppx_deriving.std)))
```

I believe that this bug can be closed.

**Comment by bikalgurung** [comment]
Yep. this can be used now.
