### ISSUE TITLE
support for OCaml 4.05

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ppx_deriving#140]

**Comment by aantron** [comment]
I believe this is tracked in #121 "4.05 support."

**Comment by ygrek** [comment]
please make a release for 4.05

**Comment by hcarty** [comment]
#141 needs a review first, ideally.

**Comment by whitequark** [comment]
Updated 4.05 support in master, still not quite ready for release. Soon™

**Comment by gasche** [comment]
4.2.1 was released today, and it should add support for 4.05 and 4.06 for users of the 4.2 version. Could the ppx_deriving users above try it and report on whether it works for them? (I'm hoping to release matching upgrades of the external plugins (protobuf, yojson etc.) this week.) One possibility is to also do a 4.1 maintenance release, if the blocking issues (mostly elsewhere in the ecosystem) haven't been fixed yet.

**Comment by emillon** [comment]
We're using 4.2.1 (4.1.5 for old compiler versions) with 4.05 and it works perfectly here.
