### ISSUE TITLE
Error: show does not support option with_path

### ISSUE THREAD

**Issue by theindigamer** [ocaml-ppx/ppx_deriving#144]
Double-checked this on switches `4.03.0` and `4.04.2+flambda`. While `[@@deriving show]` works just fine, adding in `{ with_path = false }` as in the readme results in this error.

![ppx_deriving_show](https://user-images.githubusercontent.com/7187503/28587285-995cb056-7144-11e7-85e0-758cb563b1d5.png)

Apart from this one issue, I've found the `show` functionality very easy to use and super helpful. Thanks! :smile:

**Comment by theindigamer** [comment]
A temporary work-around is using `opam pin add ppx_deriving --dev-repo`. However, it would be great if you add in the readme file what version of `ppx_deriving` should be used to be able to use the `with_path` functionality.

**Comment by whitequark** [comment]
I'll make a new release soon.

**Comment by theindigamer** [comment]
Okay, the latest release `4.2` fixes this. :smile:
