### ISSUE TITLE
Unbound value show_XXX

### ISSUE THREAD

**Issue by pe200012** [ocaml-ppx/ppx_deriving#161]
<pre>
type foo = A [@@deriving show]

let () =                                                                                                                                                         
  print_endline (show_foo A)
  (* Here has an error. *)

</pre>
The code above can be run on the toplevel, but it cannot be compiled to a native or bytecode program.
<pre>
ocamlbuild -pkg ppx_deriving.std %<.native
+ /home/pe200012/.opam/4.06.0/bin/ocamlc.opt -c -I /home/pe200012/.opam/4.06.0/lib/ppx_deriving -I /home/pe200012/.opam/4.06.0/lib/result -o main.cmo main.ml
File "main.ml", line 3, characters 15-23:
Error: Unbound value show_foo
Command exited with code 2.
Compilation unsuccessful after building 2 targets (0 cached) in 00:00:00.
</pre>

**Comment by gasche** [comment]
This looks like an error in the way you compile your code: you should add the `-use-ocamlfind` flag to get proper `ocamlfind` compatibility -- and in particular ppx preprocessing support. Either of the two commands below work correct:

```
ocamlbuild -use-ocamlfind -pkg ppx_deriving.std main.native
ocamlbuild -use-ocamlfind -tag "package(ppx_deriving.std)" main.native
```
