### ISSUE TITLE
Inconsistency between type of show in readme and source files

### ISSUE THREAD

**Issue by sapristi** [ocaml-ppx/ppx_deriving#166]
Hello, 
I noticed that the readme advertises `show` as having type `t -> bytes`, whereas the type really is string.

**Comment by gasche** [comment]
Hi @sapristi,

Nice catch! Would you like to submit a pull request to fix this?

**Comment by sapristi** [comment]
Ok I will. Should I say that  about how `ppx_deriving_runtime.ml` redefines types or leave that hidden ?

**Comment by gasche** [comment]
There are two separate things:
- Some parts of the readme use `Ppx_deriving_runtime.string` instead of `string` (or similar for other types), I would remove the mention unless necessary/important
- You could add a remark about `Ppx_deriving_runtime`, for example at the end of the "Plugin conventions" section, as a separate commit.

**Comment by sapristi** [comment]
Could you explain to me what the point of Ppx_deriving_runtime redefining types is ?

**Comment by whitequark** [comment]
Hygiene.

**Comment by gasche** [comment]
Fixed by your PR #167. Thanks!

**Comment by gasche** [comment]
Re. Hygiene: the idea is that if you are in a compilation environment that, for some reason, redefines the type `string` to be something else (sounds implausible, but it happens for modules of the standard library), the code ppx_deriving generates will still be correct as it uses `Ppx_deriving_runtime.string`, which won't be redefined.

**Comment by sapristi** [comment]
Ok thanks for the explanation.  I made another pull request for a paragraph in the "plugin conventions" section, but I guess I should rebase my commits or something like that
