### ISSUE TITLE
topkg configuration makes (wrong) assumption about installation directory

### ISSUE THREAD

**Issue by smondet** [ocaml-ppx/ppx_deriving#172]
Here: https://github.com/ocaml-ppx/ppx_deriving/blob/master/pkg/build.ml#L22

```ocaml
Pkg.bin ~auto:true "src/ppx_deriving_main" ~dst:"../lib/ppx_deriving/ppx_deriving";
```

if the instllation prefix is not called `ppx_deriving` then the above does not work

@rgrinberg will #170 fix this?

**Comment by rgrinberg** [comment]
Yes it will.

**Comment by kit-ty-kate** [comment]
The port to dune fixed this issue
