### ISSUE TITLE
maintenance feature request: CI testing of some of our reverse dependencies

### ISSUE THREAD

**Issue by gasche** [ocaml-ppx/ppx_deriving#183]
It would be nice if our CI would test the build of some of our reverse depencies (after pinning ppx_deriving), for example a couple plugins and a couple users of plugins. This could help us detecting breakage earlier in the release cycle.

(I don't have the knowledge of the best way to do that in immediate memory, so please feel free to point at an example of other project that does this, or even send a PR. Which reverse dependencies we use may depend on the opam-repository-fixing that we are in the process of doing in preparation for the 4.3 release, so I think we could wait to decide this after the release is out.)

**Comment by shonfeder** [comment]
Looks to be closed by #227

**Comment by gasche** [comment]
Indeed, thanks!
