### ISSUE TITLE
Add support for ocaml 4.08

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ppx_deriving#185]
Check https://github.com/hhugo/ppx_deriving/commit/4f807676a218f63cc64ade3a6bb1f0a9ffcf190d to see how much changes are required.

**Comment by MattWindsor91** [comment]
Is this dependent on [ppx_tools](https://github.com/ocaml-ppx/ppx_tools) getting 4.08 support?  From an outsider looking in, it's quite hard to see how bits of the ppx ecosystem depend on each other, but `ppx_tools` is the ultimate blocker as far as OPAM's dependency resolution goes.

**Comment by aatxe** [comment]
@MattWindsor91 there is an open PR on ppx_tools for 4.08 support: https://github.com/ocaml-ppx/ppx_tools/pull/70

**Comment by facelesspanda** [comment]
with ppx_tools not failing to install, I get this on ppx_deriving.
```

#=== ERROR while compiling ppx_deriving.4.3 ===================================#
# context     2.0.4 | linux/x86_64 |  | https://opam.ocaml.org#fe05883f
# path        ~/the/project/_opam/.opam-switch/build/ppx_deriving.4.3
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ppx_deriving -j 3
# exit-code   1
# env-file    ~/.opam/log/ppx_deriving-7102-00d870.env
# output-file ~/.opam/log/ppx_deriving-7102-00d870.out
### output ###
# Use Stdlib instead.
# [...]
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# File "_none_", line 1:
# Alert deprecated: module Stdlib.Pervasives
# Use Stdlib instead.
# 
# If you need to stay compatible with OCaml < 4.07, you can use the 
# stdlib-shims library: https://github.com/ocaml/stdlib-shims
# File "ppx_deriving_show.cppo.ml", line 178, characters 12-47:
# Error: The constructor Rtag expects 3 argument(s),
#        but is applied here to 4 argument(s)
```
maybe I have to pin ppx_deriving too?

**Comment by gasche** [comment]
I started to push some changes (like @hhugo's above, but trying to be backward-compatible) in a personal branch https://github.com/gasche/ppx_deriving/tree/4.08-support. Not ready yet.

I trid to investigate the deprecation warnings that show up while building ppx_deriving; I suspect that they may not all be related to the ppx_deriving codebase itself -- maybe there are parts of ppx_tools still inserting Pervasives reference. To be investigated.

**Comment by gasche** [comment]
There was indeed a ppx_tool issue: https://github.com/ocaml-ppx/ppx_tools/pull/72

**Comment by gasche** [comment]
I sent a 4.08-support PR in https://github.com/ocaml-ppx/ppx_deriving/pull/193.

**Comment by gasche** [comment]
@hhugo would you by chance be willing to review #193?

Anyone else is of course welcome. I'm also interested in reports from users trying the pin on their own 
codebase. Be sure to also take https://github.com/ocaml-ppx/ppx_tools/pull/72 with you to avoid deprecation warnings.

**Comment by aatxe** [comment]
@gasche just wanted to give an update: I'm using the pins on some of my research code, and they are working great! Happy to have both `ppx_deriving` and user-definable binding forms in the same codebase. 😄

**Comment by gasche** [comment]
Thanks! In the light of this glowing user review, I went ahead and merged the branch -- so now pinning ppx_deriving#master should be enough. I'll try to make a release next week -- leaving the issue open until that happens.

**Comment by hhugo** [comment]
can this be closed ?
