### ISSUE TITLE
Broken links on README.md

### ISSUE THREAD

**Issue by Galfour** [ocaml-ppx/ppx_deriving#208]
The following links are broken on the `README.md`:
- [eq](https://github.com/ocaml-ppx/ppx_deriving/blob/master/src_plugins/ppx_deriving_eq.cppo.ml) and [show](https://github.com/ocaml-ppx/ppx_deriving/blob/master/src_plugins/ppx_deriving_show.cppo.ml)
- [Complete API docs](http://ocaml-ppx.github.io/ppx_deriving/Ppx_deriving.html)

**Comment by gasche** [comment]
Thanks for the report! I just fixed the issue.
