### ISSUE TITLE
Optionally specifying the name of the printer produced by [@deriving show]

### ISSUE THREAD

**Issue by Kerl13** [ocaml-ppx/ppx_deriving#213]
It seems that for now it's not possible to control the name of the printer produced by `[@deriving show]`. I think it would be a nice feature to be able to control this name with a option like:
```ocaml
type t = A | B
[@deriving show {name = pp_debug}]
(* produces pp_debug: Format.formatter -> t -> unit *)
```

I'm aware this can already be emulated by defining `pp_debug` as an alias to `pp` for instance :
```ocaml
type t = A | B [@deriving show]
let pp_debug = pp
```
But this leads to a scope "polluted" with two ways of accessing the same function.

I'm also aware that it could break other printers that assume that the name of `type t = ...` is `pp` (and not the one specified by the user): 
```ocaml
type t = A | B [@deriving show {name = pp_debug}]

type u = C of t [@deriving show]
(* Breaks here because the printer for t is assumed to be named "pp" *)
```
But I think that it's fine if this is made clear in the documentation of the `show` plugin.

What is you opinion on this? I'll be happy to contribute a patch if you think it's a valuable addition to ppx_deriving :slightly_smiling_face:

**Comment by whitequark** [comment]
> But I think that it's fine if this is made clear in the documentation of the `show` plugin.

I think this makes this feature unusable for any but the simplest cases, and because of that, the added complexity is not worth the cost.

**Comment by chrismamo1** [comment]
I think the emulation/workaround you provide is sufficient for basically everyone, and this isn't a very significant quality of life improvement given the additional complexity. If you don't want the name `pp` to be overwritten then there are workarounds for that as well.

**Comment by Kerl13** [comment]
> If you don't want the name `pp` to be overwritten then there are workarounds for that as well.

I know that working around this is easy, this is not about this. I'm suggesting a simple way to customize the name without having to resort to a workaround. It admit it has limitations so I'm okay to just close the issue if this is unwanted. But I still think it'd be fine to have this feature, precisely for the simple use cases. Also I don't understand the added complexity you're referring to, I think the patch should be fairly simple.

**Comment by whitequark** [comment]
The complexity is not in the patch, but in its interaction with other features. Why is `show` so special, and this patch shouldn't touch any other deriver? Why is the inability to use the derived code elsewhere a "limitation" and not a bug? Why should we maintain this feature forever just because you needed it once?
