### ISSUE TITLE
Is it intended that attributes are fully-qualified as (e.g.) deriving.show.printer, whereas extensions are fully-qualifed as derive.show ?

### ISSUE THREAD

**Issue by chetmurthy** [ocaml-ppx/ppx_deriving#217]
I'm just curious as to the rationale for this decision.

**Comment by whitequark** [comment]
The idea was that attributes are declarative (they modify behavior) and hence use a noun (deriving), whereas extensions are imperative (they generate code in-place) and hence use a verb (derive).

**Comment by chetmurthy** [comment]
Lovely!  Thank you for the quick reply!
