### ISSUE TITLE
Various problems compiling with OCaml 4.11

### ISSUE THREAD

**Issue by rwmjones** [ocaml-ppx/ppx_deriving#219]
```
File "ppx_deriving.cppo.ml", line 102, characters 6-16:
Alert deprecated: module Option
Access modules via the Migrate_parsetree toplevel module. Use Migrate_parsetree.Option instead.
File "ppx_deriving.cppo.ml", line 168, characters 34-59:
Error: The constructor Pconst_string expects 3 argument(s),
       but is applied here to 2 argument(s)
```

I wrote this hacky downstream patch to fix these problems temporarily:
https://src.fedoraproject.org/rpms/ocaml-ppx-deriving/blob/master/f/ppx_deriving-4.4.1-ocaml-4.11.patch

**Comment by XVilka** [comment]
See https://github.com/ocaml-ppx/ppx_deriving/pull/220

**Comment by thierry-martinez** [comment]
Compiling with OCaml 4.11 is now fixed: Travis checked this in https://github.com/ocaml-ppx/ppx_deriving/pull/220 . Thanks !
