### ISSUE TITLE
Should the "eq" deriver return false on Float.nan ?

### ISSUE THREAD

**Issue by chetmurthy** [ocaml-ppx/ppx_deriving#251]
That is to say,
```
- # Float.(nan = nan) ;;
- : bool = false
```
but even so, it seems like, for the purpose to which the eq-deriver gets put (typically debugging), it might be the case that this should be `true` ?

**Comment by chetmurthy** [comment]
Or maybe it should be driven by an option?  E.g., `nan_self_equal` ?

**Comment by thierry-martinez** [comment]
I think I would prefer to define a type `float'` with a custom equality in this situation. Wouldn't this solution be enough for your use case?

**Comment by chetmurthy** [comment]
It is, and someone over at the OCaml discussion forum pointed out that I could just supply my own equality function for floats.  So it's not an actual problem, and I should have closed this issue ages ago (sorry).
