### ISSUE TITLE
How to use custom `eq` for variant?

### ISSUE THREAD

**Issue by anchpop** [ocaml-ppx/ppx_deriving#253]
From the readme:

> eq and ord allow to specify custom comparison functions for types to override default behavior. A comparator for type t has a type t -> t -> bool for eq or t -> t -> int for ord. If an ord comparator returns a value outside -1..1 range, the behavior is unspecified.
> ```ocaml
> # type file = {
>   name : string [@equal fun a b -> String.(lowercase a = lowercase b)];
>   perm : int    [@compare fun a b -> compare b a]
> } [@@deriving eq, ord];;
> ```

But when I try:
```ocaml
type test = Foo
type all_messed_up = Boo of test [@equal fun a b -> true] [@@deriving eq]
```
That results in this error:
```
2 | type all_messed_up = Boo of test [@equal fun a b -> true] [@@deriving eq]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value equal_test
```
Am I using it wrong, or does it not work for variants? (It'd be confusing if it didn't, because `printer` does work for variants)

**Comment by kit-ty-kate** [comment]
> ```ocaml
> type test = Foo
> type all_messed_up = Boo of test [@equal fun a b -> true] [@@deriving eq]
> ```

```
type test = Foo
type all_messed_up = Boo of (test [@equal fun a b -> true]) [@@deriving eq]
```
with parenthesis works.

I'm guessing `[@attribute]` attaches to `Boo of test` and not to `test`.

This is probably something that could be fixed indeed (unless `[@equal ]` on a variant itself has a meaning already)

**Comment by anchpop** [comment]
Oh, that's great, thank you
