### ISSUE TITLE
[E] Unbound type constructor Result.result

### ISSUE THREAD

**Issue by concatime** [ocaml-ppx/ppx_deriving#257]
Hi.
I'm trying to bootstrap [FStar](https://github.com/FStarLang/FStar) and it depends on ppx_deriving.
When trying to build `v5.2.1`, I get:
```
File "ppx_deriving.cppo.mli", line 109, characters 44-57:
Error: Unbound type constructor Result.result
```
I'm using the latest versions: `OCaml@4.13.1`, `dune@2.9.3`, `cppo@1.6.8`, `ppx_derivers@1.2.1` and `ppxlib@0.24.0`.
I’m very unfamiliar with OCaml environment, so bear with me :)

**Comment by gasche** [comment]
`Result.result` comes from the [result](https://github.com/janestreet/result) package, do you have it installed? (Are you using the standard build instructions for ppx_deriving, or something different? It's strange that there is no complaint as it is listed as a dependency.)

I wonder if we shouldn't use `Result.t` instead, which should be equivalent and may work properly without the `result` package on recent-enough OCaml versions.

**Comment by kit-ty-kate** [comment]
> It's strange that there is no complaint as it is listed as a dependency.)

I believe this is a consequance of a bug in dune fixed in dune 3.0.0: https://github.com/ocaml/dune/pull/4946
The issue is that with dune < 3 the `result` library is a builtin in dune and so if it is used but not installed it will be defined as empty and will not contain `Result.result` (from older versions of the result compat library)

We could use `Result.t` indeed but we must not forget to add `{>= "1.5"}` to the `result` constraints.

**Comment by concatime** [comment]
Well, you nailed it folks!
But now, after adding the `result` package, I get:
```
File "_none_", line 1:
Warning 58 [no-cmx-file]: no cmx file was found in path for module Dynlink, and its interface was not compiled with -opaque
File "_none_", line 1:
Warning 58 [no-cmx-file]: no cmx file was found in path for module Dynlink, and its interface was not compiled with -opaque
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Dynlink referenced from /opt/ocaml/lib/ocaml/site-lib/findlib/findlib_dynload.cmxa(Fl_dynload),
           src/.ppx_deriving_main.eobjs/native/findlib_initl.cmx,
           src/.ppx_deriving_main.eobjs/native/ppx_deriving_main.cmx
```

**Comment by kit-ty-kate** [comment]
You can see the list of all the requirements here: https://github.com/ocaml-ppx/ppx_deriving/blob/master/ppx_deriving.opam

**Comment by concatime** [comment]
Well, I was building OCaml with `--enable-shared=no --enable-static=yes`. It seems that ppx_deriving REQUIRES `--enable-shared=yes`. Am I right?

**Comment by kit-ty-kate** [comment]
ah yes, that’s correct. Most OCaml package will break without shared library support

**Comment by concatime** [comment]
Ok, thank you.
